### ISSUE TITLE
Fix throughput issue

### ISSUE THREAD

**Issue by katyhuff** [arfc/recycle#5]
https://github.com/arfc/recycle/pull/3/files#diff-34431d09eed18214c3be98b2ffe95fe5R27

Something funky this way comes ^^^ 

Figure out what you were trying to do and do that thing properly. Otherwise, just delete the line.
This issue can be closed when a PR is merged that deals with this line.

**Comment by gtw2** [comment]
Removed with #6 - line and variable were redundant.
